# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c01cf7b55fb87207505b25ab7a1d9ff7d3305d5cd1dd890ac416789bdd69de7d9fe593ecf272af06092f7c8687476a2a0c00fadfe7d8924cb4c6fd6f98adb1e2

test:
  secret_key_base: 5ee6331685158b26dcaa0cc6966f3c06b93040aeae10e18a42b514f08c19f8d05bce51b9009b298ec01aacfde3ad3dd1e58722d4cdcf2c1ff440e4cce8cf8e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
